/**
 * Shared types for all agents in the CI/CD pipeline
 */

import * as crypto from 'crypto';

export type AgentName = 'iac-agent' | 'cicd-agent' | 'security-agent' | 'observer-agent';

export type ActionType =
  | 'plan_infra'
  | 'apply_infra'
  | 'verify_pipeline'
  | 'rerun_pipeline'
  | 'block_pr'
  | 'approve_security'
  | 'unknown';

export type Scope = 'test' | 'staging' | 'prod';

export type DecisionStatus = 'allow' | 'deny' | 'conditional';

/**
 * Intent generated by an agent
 */
export interface AgentIntent {
  agent: AgentName;
  action: ActionType;
  target: string;
  scope: Scope;
  timestamp: string;
  evidence: Evidence[];
  metadata?: Record<string, unknown>;
}

/**
 * Evidence supporting an intent
 */
export interface Evidence {
  type: 'changed_files' | 'test_output' | 'audit_output' | 'git_context' | 'environment';
  source: string;
  summary: string;
  data?: unknown;
}

/**
 * Decision made by the observer agent
 */
export interface AgentDecision {
  intent_hash: string;
  agent: AgentName;
  action: ActionType;
  scope: Scope;
  decision: DecisionStatus;
  policy_rule_applied: string;
  reason: string;
  timestamp: string;
  evidence: Evidence[];
  requires_approval?: boolean;
}

/**
 * Policy rule from agent-policies.yaml
 */
export interface PolicyRule {
  action: ActionType | '*';
  scope?: Scope | '*' | { not: Scope };
  decision: DecisionStatus;
  reason?: string;
}

/**
 * Agent policy configuration
 */
export interface AgentPolicy {
  rules: PolicyRule[];
}

/**
 * Full policies configuration
 */
export interface PoliciesConfig {
  'iac-agent'?: AgentPolicy;
  'cicd-agent'?: AgentPolicy;
  'security-agent'?: AgentPolicy;
  default?: AgentPolicy;
}

/**
 * GitHub Actions context variables
 */
export interface GitHubContext {
  sha: string;
  ref: string;
  runId: string;
  runNumber: string;
  actor: string;
  eventName: string;
  repository: string;
  prNumber?: string;
  baseSha?: string;
  headSha?: string;
}

/**
 * Get GitHub context from environment variables
 */
export function getGitHubContext(): GitHubContext {
  return {
    sha: process.env.GITHUB_SHA || 'local',
    ref: process.env.GITHUB_REF || 'refs/heads/local',
    runId: process.env.GITHUB_RUN_ID || 'local-run',
    runNumber: process.env.GITHUB_RUN_NUMBER || '0',
    actor: process.env.GITHUB_ACTOR || 'local-user',
    eventName: process.env.GITHUB_EVENT_NAME || 'local',
    repository: process.env.GITHUB_REPOSITORY || 'local/repo',
    prNumber: process.env.GITHUB_PR_NUMBER,
    baseSha: process.env.GITHUB_BASE_SHA,
    headSha: process.env.GITHUB_HEAD_SHA,
  };
}

/**
 * Compute a hash for an intent (for audit trail)
 */
export function computeIntentHash(intent: AgentIntent): string {
  const data = JSON.stringify({
    agent: intent.agent,
    action: intent.action,
    target: intent.target,
    scope: intent.scope,
    timestamp: intent.timestamp,
  });
  return crypto.createHash('sha256').update(data).digest('hex').substring(0, 16);
}
